<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'User "{name}" successfully created' => 'Usuário "{name}" criado com sucesso',
    'Username' => 'Nome de usuário',
    'Password' => 'Senha',
    'Name' => 'Nome',
    'Invalid CPF' => 'CPF inválido',
    'Username and password must not be empty' => 'Nome de usuário e senha não devem estar vazios',
    'Invalid username or password' => 'Nome de usuário ou senha inválidos',
    'Invalid or expired token' => 'Token inválido ou expirado',
    'Error saving user tokens' => 'Erro ao salvar os tokens do usuário',
    'Customer deleted successfully' => 'Cliente removido com sucesso',
    'Product deleted successfully' => 'Produto removido com sucesso',
    'Customer not found' => 'Cliente não encontrado',
    'Product not found' => 'Produto não encontrado',
];
